A/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls' , namespace='home')),
    path('account/',include('account.urls', namespace='account')),
]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/',views.RegisterView.as_view(), name = "user_register"),
    path('login/',views.LoginView.as_view(), name = "user_login"),
    path('logout/',views.LogoutView.as_view(), name = "user_logout"),
    path('profile/<int:user_id>',views.ProfileView.as_view(), name = "user_profile"),
    path('reset/',views.UserPasswordResetView.as_view(), name = "reset_password"),
    path('reset/done/',views.UserPasswordResetDoneView.as_view(), name = "password_reset_done"),
    path('confirm/<uidb64>/<token>/',views.UserPasswordResetConfirmView.as_view(), name = "password_reset_confirm"),
    path('confirm/complete/',views.UserPasswordResetCompleteView.as_view(), name = "password_reset_complete"),
    path('follow/<int:user_id>/',views.UserFollowView.as_view(), name = "user_follow"),
    path('unfollow/<int:user_id>/',views.UserUnfollowView.as_view(), name = "user_unfollow"),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view() , name = 'home'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view() , name = 'post_detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view() , name = 'post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view() , name = 'post_update'),
    path('post/create/', views.PostCreateView.as_view() , name = 'post_create'),
    path('reply/<int:post_id/<int:comment_id/', views.PostAddReplyView.as_view() , name = 'add_reply'),
    path('like/<int:post_id/', views.PostLikeView.as_view() , name = 'post_like'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    objects = True
    user = models.ForeignKey(User , on_delete=models.CASCADE , related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updates = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-body',)


    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('home:post_detail' , args=(self.id, self.slug))


class Comment (models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Post , on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('self' , on_delete=models.CASCADE, related_name='rcomments' , blank=True , null=True)
    is_reply = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    body = models.TextField(max_length=400)


    def __str__(self):
        return f'{self.user} - {self.body[:30]}'




class Vote(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE , related_name='uvotes')
    post = models.ForeignKey(Post , on_delete=models.CASCADE , related_name='pvotes')

    def __str__(self):
        return f'{self.user} liked{self.post.slug}'

home/forms.py
from django import forms
from .models import Post , Comment


class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)
class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
             'body' : forms.Textarea(attrs={'class' : 'form-control'})


         }

class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

home/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.views import View
from .models import Post , Comment , Vote
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import PostCreateUpdateForm
from django.utils.text import slugify
from .forms import CommentCreateForm , CommentReplyForm

class HomeView(View):
    def get(self , request):
        posts = Post.objects.all()
        return render(request ,'home/index.html' , {'posts':posts})


class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request , *args ,**kwargs)


    def get(self , request , *args , **kwargs):

        comments = self.post_instance.pcomments.filter(is_reply =False)
        return render(request , 'home/detail.html' , {'post':self.post_instance , 'comments':comments , 'form':self.form_class , 'reply_form' : self.form_class_reply})

    def post(self , request , *args , **kwargs):
            form = self.form_class(request.POST)
            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.user = request.user
                new_comment.post = self.post_instance
                new_comment.save()
                messages.success(request , 'your comment submit successfully' , 'success')

            return redirect('home:post_detail' , self.post_instance.id , self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin,View):
    def get(self ,request , post_id):
        post = Post.objects.get(pk = post_id)
        if post.user.id == request.user.id :
            post.delete()
            messages.success(request , 'your post deleted' , 'success')
        else :
            messages.error(request , 'you cant delete this post' , 'danger')

        return redirect('home:home')

class PostUpdateView(LoginRequiredMixin,View):
    form_class = PostCreateUpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
       post = self.post_instance
       if not post.user.id == request.user.id:
           messages.error(request , 'you cant update this post' , 'danger')
           return redirect('home:home')
       return super().dispatch( request, *args, **kwargs)

    def get(self , request , *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request , 'home/update.html', {'form':form})
    def post(self , request , *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST , instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request , 'your updated successfully' , 'success')
            return redirect('home:post_detail' , post.id , post.slug)



class PostCreateView (LoginRequiredMixin ,View):
    form_class = PostCreateUpdateForm
    def get(self ,request , *args , **kwargs):
        form = self.form_class
        return render(request,'home/create.html',{'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request , 'your create post is successfully' , 'success')
            return redirect('home:post_detail' , new_post.id , new_post.slug)


class PostAddReplyView(LoginRequiredMixin , View):
    form_class = CommentReplyForm
    def post(self , requset , post_id  , comment_id ):
        post =  get_object_or_404(Post , id = post_id)
        comment = get_object_or_404(Comment , id = comment_id )
        form = self.form_class(requset.POST)
        if form.is_valid():
            reply = form.save   (commit=False)
            reply.user = requset.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(requset , "your reply is successfully " , 'success')
        return redirect('home:post_detail' , post.id , post.slug)


class PostLikeView(LoginRequiredMixin , View):
    def get(self , request , post_id):
        post = get_object_or_404(Post , id=post_id)
        like = Vote.objects.filter(post=post , user=request.user)
        if like.exists():
            messages.error(request , 'you liked this post already' , 'danger')
        else:
            Vote.objects.create(post=post , user=request.user)
            messages.success(request , 'you liked this post' , 'success')
        return redirect('home:post_detail' , post.id ,  post.slug )

home/templates/home/create.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
       <input type="submit" value="create">
        
        
    </form>
{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
    
    {% if request.user.id == post.user.id %}
        <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'home:post_update' post.id %}" class="btn btn-info">Update</a>
    {% endif %}

    <h4><a href="{% url 'account:user_profile' post.user.id %}">{{post.user.username}}<a/> - {{ post.updates|date:"Y-M"}}</h4>
    <h1 class="text-center">{{post.body}}</h1><hr>




    {% if request.user.is_authenticated %}

        <a href="{% url 'home:post_like' post.id %}" class="btn btn-primary col-md-2">like</a>

        <form action="" method="post"></form>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
    {% else %}
        <p class="alert alert-danger">only logged in users can comment. </p>

    {% endif %}


    {% for comment in comments %}
    
        <div class="card bg-dark text-white"></div>
            <p class="card-header">{{ comment.user }} | {{ comment.created }}</p>
            <p class="card-body">{{ comment.body }}</p>
            {% if request.user.is_authenticated %}
            
                <form action="" method="post">
                    {% csrf_token %}
                    {{ reply_form.as_p }}
                    <input type="submit" value="Send">
                </form>
                

            {% endif %}

            

            
            {% for reply in comment.rcomments.all %}
                <p class="bg-primary p-3 m-2">{{ reply.user }} - {{ reply.body }}</p>
            {% endfor %}
    {% empty %}
        <p>No comment yet!</p>
    {% endfor %}

{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
<h2> main page </h2>

    <div class="card">
        {% for post in posts %}
            <a href="{{post.get_absolute_url}}" class="card-body">{{post.body}}</a>
    
         {% endfor %}
    </div>




{% endblock %}

home/templates/home/update.html
{% extends 'base.html '%}

{% block content %}

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
        
    </form>

{% endblock %}